### PR TITLE
Fix timezone inconsistencies

### PR DESCRIPTION
**Pull request by ZipFile**
Fixes `TypeError` in:

```python
from sonyflake.sonyflake import SonyFlake, SONYFLAKE_EPOCH
SonyFlake(SONYFLAKE_EPOCH)
```

### CODE REVIEW

**Comment by hjpotter92** [comment]
> Fixes `TypeError` in:
> 
> ```python
> from sonyflake.sonyflake import SonyFlake, SONYFLAKE_EPOCH
> SonyFlake(SONYFLAKE_EPOCH)
> ```

Hey, thanks for the fix. Could you also add a short info in the [changelog](https://github.com/hjpotter92/sonyflake-py/blob/master/docs/src/changelog.md)?

**Comment by ZipFile** [comment]
What the format for unreleased changes? Or should I just bump the version along with introducing changelog entry?

**Comment by hjpotter92** [comment]
There's no format as of now. You can chose either strategy :)

**Comment by ZipFile** [comment]
Done.

**Pull request merged**
